# This is a set of bank ids manually harvested from wikidata.
# it is used in the source data
from collections import defaultdict

id_map = {'bnp_paribas': 
   {'permid': '8589934326',
    'isin': 'FR0000131104',
    'viafid': '124434551',
    'lei': 'R0MUWSFPU8MPRO8K5P83'},
 'abn_amro': {'permid': None,
  'isin': 'NL0011540547',
  'viafid': '138658025',
  'lei': 'BFXS5XCH7N0Y05NIXW11'},
 'anz': {'permid': None,
  'isin': 'AU000000ANZ3',
  'viafid': '157469879',
  'lei': None},
 'banco_bradesco': {'permid': '4295859689',
  'isin': 'BRBBDCACNPR8',
  'viafid': None,
  'lei': None},
 'banco_do_brasil': {'permid': None,
  'isin': 'BRBBASACNOR3',
  'viafid': '135398201',
  'lei': 'QE0Q0253K88YAGNPE356'},
 'itau_unibanco': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'santander': {'permid': None,
  'isin': 'US05967A1079',
  'viafid': '135478920',
  'lei': None},
 'bank_mandiri': {'permid': None,
  'isin': None,
  'viafid': '138397688',
  'lei': None},
 'bank_of_america': {'permid': '8589934339',
  'isin': 'US0605051046',
  'viafid': None,
  'lei': '9DJT3UXIJIZJI4WXO774'},
 'bank_of_china': {'permid': '4295863670',
  'isin': 'CNE1000001Z5',
  'viafid': '138344203',
  'lei': None},
 'barclays': {'permid': '8589934333',
  'isin': 'GB0031348658',
  'viafid': '146326270',
  'lei': 'G5GSEF7VJP5I7OUK5573'},
 'bank_of_tokyo_mitsubishi_ufj': {'permid': '5000000933',
  'isin': 'JP3902900004',
  'viafid': '139116961',
  'lei': None},
 'citi': {'permid': '4297188446',
  'isin': 'US1729674242',
  'viafid': '158647664',
  'lei': '6SHGI4ZSSLCXXQSBB395'},
 'credit_suisse': {'permid': '4295890672',
  'isin': 'CH0012138530',
  'viafid': '154496717',
  'lei': '549300506SI9CRFV9Z86'},
 'deutsche_bank': {'permid': '4295869482',
  'isin': 'DE0005140008',
  'viafid': '130112035',
  'lei': '7LTWFZYICNSX8D621K86'},
 'goldman_sachs': {'permid': '4295911963',
  'isin': 'US38141G1040',
  'viafid': '136070081',
  'lei': '784F5XWPLTWKTBV3E584'},
 'hsbc': {'permid': '8589934275',
  'isin': 'GB0005405286',
  'viafid': '152107418',
  'lei': 'MLU0ZO3ML4LN2LL2TL39'},
 'jpmorgan_chase': {'permid': '5000021791',
  'isin': 'US46625H1005',
  'viafid': '126697014',
  'lei': '8I5DZWZKVSZI1NUHU748'},
 'societe_generale': {'permid': '5000039357',
  'isin': 'FR0000130809',
  'viafid': '126113318',
  'lei': '9695009HXSFK8D6V0T62'},
 'belfius': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'ing': {'permid': '4295884647',
  'isin': 'NL0011821202',
  'viafid': '172150645',
  'lei': '549300NYKK9MWM7GGW15'},
 'intesa_sanpaolo': {'permid': None,
  'isin': 'IT0000072618',
  'viafid': '311582859',
  'lei': None},
 'sumitomo_mitsui_banking_corporation': {'permid': None,
  'isin': None,
  'viafid': '145762586',
  'lei': '5U0XI89JRFVHWIBS4F54'},
 'fubon_financial_holdings': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'mizuho': {'permid': '4295878505',
  'isin': 'JP3885780001',
  'viafid': '137575591',
  'lei': None},
 'westpac': {'permid': '4295856627',
  'isin': 'AU000000WBC1',
  'viafid': '144276168',
  'lei': None},
 'ubs': {'permid': '4295890710',
  'isin': 'CH0244767585',
  'viafid': '122312097',
  'lei': '549300SZJ9VS8SGXAN81'},
 'standard_chartered': {'permid': '4295895205',
  'isin': 'GB0004082847',
  'viafid': '167903634',
  'lei': None},
 'kbc': {'permid': '8589934262',
  'isin': 'BE0003565737',
  'viafid': '133559380',
  'lei': '213800X3Q9LSAKRUWY91'},
 'bbva': {'permid': '4295889577',
  'isin': 'ES0113211835',
  'viafid': '156510810',
  'lei': 'K8MS7FD7N5Z2WQ51AZ71'},
 'morgan_stanley': {'permid': '4295904557',
  'isin': 'US6174464486',
  'viafid': '136233836',
  'lei': 'IGJSJL3JD5P30I6NJZ34'},
 'nedbank': {'permid': None,
  'isin': 'ZAE000004875',
  'viafid': '123310681',
  'lei': None},
 'rabobank': {'permid': '4297066570',
  'isin': None,
  'viafid': '193512698',
  'lei': '549300CSSXBX5D7HKJ69'},
 'rbc': {'permid': '8589934213',
  'isin': 'CA7800871021',
  'viafid': '143038350',
  'lei': None},
 'natwest': {'permid': None, 'isin': None, 'viafid': '128259943', 'lei': None},
 'scotiabank': {'permid': '4295860592',
  'isin': 'CA0641491075',
  'viafid': '140736355',
  'lei': None},
 'china_construction_bank': {'permid': None,
  'isin': 'CNE1000002H1',
  'viafid': None,
  'lei': None},
 'industrial_commercial_bank_of_china': {'permid': '4295863742',
  'isin': 'CNE1000003G1',
  'viafid': '150532306',
  'lei': '5493002ERZU2K9PZDL40'},
 'state_bank_of_india': {'permid': None,
  'isin': 'US8565522039',
  'viafid': '138999607',
  'lei': None},
 'standard_bank': {'permid': '4295889219',
  'isin': 'ZAE000109815',
  'viafid': None,
  'lei': None},
 'credit_agricole': {'permid': None,
  'isin': 'FR0000045072',
  'viafid': '209916632',
  'lei': '969500TJ5KRTCJQWXH05'},
 'unicredit': {'permid': '4295875726',
  'isin': 'IT0005239360',
  'viafid': '152818686',
  'lei': None},
 'banco_galicia': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bmo_financial_group': {'permid': '4295860596',
  'isin': 'CA0636711016',
  'viafid': '128949090',
  'lei': None},
 'banca_etica': {'permid': None,
  'isin': None,
  'viafid': '145824468',
  'lei': '549300DI8RATWW2KQO25'},
 'alternative_bank_schweiz': {'permid': None,
  'isin': None,
  'viafid': '155520127',
  'lei': None},
 'asn_bank': {'permid': None,
  'isin': '310514100',
  'viafid': None,
  'lei': '72450040OXLISL2H6B31'},
 'de_volksbank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': '724500BIDCUGRAIG8681'},
 'gls_bank': {'permid': None,
  'isin': None,
  'viafid': '137881269',
  'lei': '52990026HQOTT4AJP655'},
 'macquarie_group': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'op_financial_group': {'permid': None,
  'isin': None,
  'viafid': '3145602305301360934',
  'lei': None},
 'btg_pactual': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'the_co_operative_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'rsf_social_finance': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'caixa_economica_federal': {'permid': None,
  'isin': None,
  'viafid': '159907880',
  'lei': None},
 'CaixaBank': {'permid': None,
  'isin': 'ES0140609019',
  'viafid': '127853805',
  'lei': None},
 'banco_popular_espanol': {'permid': None,
  'isin': 'ES0113790531',
  'viafid': '133985195',
  'lei': None},
 'banco_espirito_santo': {'permid': None,
  'isin': None,
  'viafid': '315536882',
  'lei': None},
 'caisse_de_economie_solidaire_desjardins': {'permid': None,
  'isin': None,
  'viafid': '137160672',
  'lei': None},
 'ekobanken': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'china_development_bank': {'permid': None,
  'isin': None,
  'viafid': '123499081',
  'lei': None},
 'first_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'attijariwafa_bank': {'permid': None,
  'isin': None,
  'viafid': '263905602',
  'lei': None},
 'commercial_international_bank_cib': {'permid': None,
  'isin': None,
  'viafid': '892155044764072520003',
  'lei': None},
 'postal_savings_bank_of_china': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'national_bank_of_egypt': {'permid': None,
  'isin': None,
  'viafid': '140255791',
  'lei': None},
 'jyske_bank': {'permid': '8589934264',
  'isin': 'DK0010307958',
  'viafid': '134439481',
  'lei': None},
 'sydbank': {'permid': '4295865860',
  'isin': 'DK0010311471',
  'viafid': '159240174',
  'lei': 'GP5DT10VX1QRQUKVBK64'},
 'sparebank_1_srbank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banque_populaire': {'permid': None,
  'isin': None,
  'viafid': '139125415',
  'lei': 'NICH5Q04ADUV9SN3Q390'},
 'china_exim_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'china_everbright_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'cibc': {'permid': '4295860600',
  'isin': 'CA1360691010',
  'viafid': '133608301',
  'lei': None},
 'manulife': {'permid': '4295862758',
  'isin': 'CA56501R1064',
  'viafid': '157051628',
  'lei': None},
 'nordea': {'permid': '5000062056',
  'isin': 'SE0000427361',
  'viafid': '128176191',
  'lei': None},
 'zurich_kantonalbank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'td_bank_financial_group': {'permid': '4295862902',
  'isin': 'CA8911605092',
  'viafid': '140638307',
  'lei': 'PT3QB789TSUIDF371261'},
 'danske_bank': {'permid': '8589934305',
  'isin': 'DK0010274414',
  'viafid': '150389001',
  'lei': 'MAES062Z21O4RZ2U7M96'},
 'erste_group': {'permid': None,
  'isin': 'AT0000652011',
  'viafid': None,
  'lei': 'PQOH26KWDF7CG10L6792'},
 'wells_fargo': {'permid': '8589934175',
  'isin': 'US9497461015',
  'viafid': '132150619',
  'lei': 'PBLD0EJDB5FWOLXP3B76'},
 'commonwealth_bank': {'permid': None,
  'isin': 'AU000000CBA7',
  'viafid': '140880224',
  'lei': None},
 'national_australia_bank_group': {'permid': '4295857405',
  'isin': 'AU000000NAB4',
  'viafid': None,
  'lei': None},
 'dekabank': {'permid': None,
  'isin': None,
  'viafid': '158641040',
  'lei': '0W2PZJM8XOY22M4GG883'},
 'natixis': {'permid': '5000016911',
  'isin': 'FR0000120685',
  'viafid': '127093143',
  'lei': 'KX1WK48MPD4Y2NCUIZ63'},
 'commerzbank': {'permid': None,
  'isin': 'DE000CBK1001',
  'viafid': '124326234',
  'lei': '851WYGNLUQLFZBSYGB56'},
 'industrial_bank': {'permid': None,
  'isin': 'CNE000001QZ7',
  'viafid': None,
  'lei': None},
 'bangkok_bank': {'permid': '4295893055',
  'isin': 'TH0001010014',
  'viafid': '146028748',
  'lei': None},
 'kasikorn_bank': {'permid': None,
  'isin': 'TH0016010009',
  'viafid': None,
  'lei': None},
 'absa_bank_limited': {'permid': None,
  'isin': 'ZAE000255915',
  'viafid': '124515447',
  'lei': '2138006IPPRD4N6XLT30'},
 'access_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'arab_african_international_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_de_la_republica_oriental_del_uruguay': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'export_import_bank_of_india': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bancolombia_s_a_': {'permid': '4295865713',
  'isin': 'US05968L1026',
  'viafid': None,
  'lei': '54930052NWJRPNMP1W58'},
 'bank_muscat': {'permid': None,
  'isin': 'US0637462005',
  'viafid': None,
  'lei': None},
 'corpbanca': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'dnb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'export_development_canada': {'permid': None,
  'isin': None,
  'viafid': '131302344',
  'lei': None},
 'firstrand_group_ltd': {'permid': None,
  'isin': 'ZAE000066304',
  'viafid': None,
  'lei': None},
 'fmo': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'kfw_ipex_bank': {'permid': None,
  'isin': None,
  'viafid': '133494153',
  'lei': '529900Q1M1F4M8KMTM64'},
 'lloyds_banking_group_plc': {'permid': None,
  'isin': None,
  'viafid': '604145857930923020007',
  'lei': None},
 'seb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bnp_paribas_fortis': {'permid': None,
  'isin': None,
  'viafid': '501145857935623021548',
  'lei': None},
 'garantibank': {'permid': None,
  'isin': None,
  'viafid': '141248415',
  'lei': None},
 'akbank': {'permid': None,
  'isin': 'TRAAKBNK91N6',
  'viafid': '153052315',
  'lei': None},
 'bmce_bank': {'permid': None,
  'isin': None,
  'viafid': '148350602',
  'lei': None},
 'agricultural_bank_of_china': {'permid': '5000014265',
  'isin': 'CNE100000Q43',
  'viafid': '151280770',
  'lei': None},
 'kb_financial_group': {'permid': '4295881997',
  'isin': 'KR7060000007',
  'viafid': '167633093',
  'lei': '549300XXMOJSIW8P4769'},
 'pnc': {'permid': '4295904676',
  'isin': 'US6934751057',
  'viafid': '138738904',
  'lei': 'CFGNEKW0P8842LEUIA51'},
 'cifi': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'shinhan_financial_group': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'yuanta_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'shinsei_bank': {'permid': None,
  'isin': None,
  'viafid': '125717045',
  'lei': '549300PZYOQ2NW83V760'},
 'mianyang_city_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'ctbc_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'chongqing_rural_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_sinopac': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_huzhou': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'nibc': {'permid': None, 'isin': 'NL0012756316', 'viafid': None, 'lei': None},
 'ahli_united_bank': {'permid': None,
  'isin': None,
  'viafid': '138729262',
  'lei': None},
 'vnesheconombank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sberbank': {'permid': '5000036115',
  'isin': 'RU0009029540',
  'viafid': '145578847',
  'lei': None},
 'bank_of_communications': {'permid': '4295864463',
  'isin': 'CNE100000205',
  'viafid': '152417975',
  'lei': None},
 'hua_xia_bank': {'permid': None,
  'isin': 'CNE000001FW7',
  'viafid': None,
  'lei': None},
 'china_merchants_bank': {'permid': None,
  'isin': 'CN000A0KFDV9',
  'viafid': '151513516',
  'lei': None},
 'shanghai_pudong_development_bank': {'permid': None,
  'isin': 'CN0009282731',
  'viafid': None,
  'lei': None},
 'china_minsheng_bank': {'permid': '4295864351',
  'isin': 'CN0005910772',
  'viafid': None,
  'lei': None},
 'citic_bank_international': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'axis_bank': {'permid': '4295873131',
  'isin': 'INE238A01034',
  'viafid': None,
  'lei': None},
 'industrial_development_bank_of_india': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'alfa_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'hdfc_bank': {'permid': None,
  'isin': 'US40415F1015',
  'viafid': '296515954',
  'lei': None},
 'icici_bank': {'permid': '4295873612',
  'isin': 'INE090A01021',
  'viafid': '151888568',
  'lei': None},
 'china_citic_bank': {'permid': None,
  'isin': 'CNE1000001Q4',
  'viafid': '308214589',
  'lei': None},
 'ping_an_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_beijing': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_of_ningbo': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_nanjing': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'vtb_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'maybank': {'permid': None,
  'isin': 'MYL1155OO000',
  'viafid': None,
  'lei': None},
 'banque_misr': {'permid': None,
  'isin': None,
  'viafid': '144268580',
  'lei': None},
 'cimb': {'permid': '4295883663',
  'isin': 'MYL1023OO000',
  'viafid': None,
  'lei': None},
 'dbs': {'permid': None,
  'isin': 'SG1L01001701',
  'viafid': '137728933',
  'lei': None},
 'ocbc': {'permid': None, 'isin': None, 'viafid': '159509971', 'lei': None},
 'uob': {'permid': None,
  'isin': 'SG1M31001969',
  'viafid': '135241015',
  'lei': None},
 'bank_negara_indonesia': {'permid': None,
  'isin': None,
  'viafid': '155277250',
  'lei': None},
 'bank_rakyat_indonesia': {'permid': None,
  'isin': 'ID1000118201',
  'viafid': '156682623',
  'lei': None},
 'idfc': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'otkritie_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'banco_de_credito_del_peru_bcp_': {'permid': None,
  'isin': None,
  'viafid': '124024818',
  'lei': None},
 'dz_bank': {'permid': None,
  'isin': None,
  'viafid': '152222027',
  'lei': '529900HNOAA1KXQJUQ27'},
 'korea_development_bank_kdc': {'permid': None,
  'isin': None,
  'viafid': '146246775',
  'lei': None},
 'the_norinchukin_bank': {'permid': None,
  'isin': None,
  'viafid': '151114810',
  'lei': None},
 'bny_mellon': {'permid': '5000767359',
  'isin': 'US0640581007',
  'viafid': '128101613',
  'lei': 'WFLLPEPC7FZXENRZV188'},
 'us_bancorp': {'permid': '8589934183',
  'isin': 'US9029733048',
  'viafid': '159500123',
  'lei': 'N1GZ7BBF3NP8GI976H15'},
 'suncorp': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'la_banque_postale': {'permid': None,
  'isin': None,
  'viafid': '154010259',
  'lei': '96950066U5XAAIRCPA78'},
 'allianz': {'permid': None,
  'isin': 'DE0008404005',
  'viafid': '139402204',
  'lei': '529900K9B0N5BT694847'},
 'bayernlb': {'permid': None,
  'isin': None,
  'viafid': '148997918',
  'lei': 'VDYMYTQGZZ6DU0912C88'},
 'helaba': {'permid': None,
  'isin': None,
  'viafid': '135048980',
  'lei': 'DIZES5CFO5K3I5R58746'},
 'hsh_nordbank': {'permid': None,
  'isin': None,
  'viafid': '141685953',
  'lei': 'TUKDD90GPC79G1KOE162'},
 'lbbw': {'permid': None,
  'isin': None,
  'viafid': '125932340',
  'lei': 'B81CK4ESI35472RHJ606'},
 'zenith_bank': {'permid': None,
  'isin': 'US98935J1025',
  'viafid': None,
  'lei': None},
 'norddeutsche_landesbank_nordlb_': {'permid': None,
  'isin': None,
  'viafid': '150746472',
  'lei': 'DSNHHQ2B9X5N6OUJ1236'},
 'mediobanca': {'permid': None,
  'isin': 'IT0000062957',
  'viafid': '139091711',
  'lei': None},
 'raiffeisen_zentralbank': {'permid': None,
  'isin': 'AT0000606306',
  'viafid': '2315150808953019000004',
  'lei': None},
 'swedbank': {'permid': None,
  'isin': 'SE0000242455',
  'viafid': '137788354',
  'lei': 'M312WZV08Y7LYUC71685'},
 'bank_of_india': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'power_finance_corporation': {'permid': None,
  'isin': None,
  'viafid': '123276901',
  'lei': None},
 'life_insurance_corporation_of_india': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'pko_bank_polski': {'permid': None,
  'isin': 'PLPKO0000016',
  'viafid': '127219974',
  'lei': None},
 'bank_gospodarstwa_krajowego': {'permid': None,
  'isin': None,
  'viafid': '264680853',
  'lei': None},
 'getin_noble_bank': {'permid': None,
  'isin': None,
  'viafid': '303510267',
  'lei': None},
 'bank_millennium': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_central_asia': {'permid': None,
  'isin': 'ID1000109507',
  'viafid': '137532084',
  'lei': None},
 'bank_danamon': {'permid': None,
  'isin': None,
  'viafid': '133918642',
  'lei': None},
 'bank_gospodarki_ywno_ciowej': {'permid': None,
  'isin': None,
  'viafid': '166986793',
  'lei': None},
 'credit_mutuel': {'permid': None,
  'isin': None,
  'viafid': '156834573',
  'lei': None},
 'bndes': {'permid': None, 'isin': None, 'viafid': '148368881', 'lei': None},
 'bankia': {'permid': None,
  'isin': 'ES0113307021',
  'viafid': '249388196',
  'lei': '549300685QG7DJS55M76'},
 'norges_bank': {'permid': None,
  'isin': None,
  'viafid': '140684568',
  'lei': None},
 'kfw': {'permid': None,
  'isin': None,
  'viafid': '156661252',
  'lei': '549300GDPG70E3MBBU98'},
 'bpce_group': {'permid': None,
  'isin': 'FR0010871269',
  'viafid': '170249927',
  'lei': None},
 'wing_lung_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'cathay_united_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sumitomo_mitsui_trust_holdings': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_sabadell': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_hapoalim': {'permid': None,
  'isin': 'IL0006625771',
  'viafid': '134562293',
  'lei': None},
 'finnfund': {'permid': None,
  'isin': None,
  'viafid': '168201535',
  'lei': None},
 'bank_leumi': {'permid': None,
  'isin': 'IL0006046119',
  'viafid': '138402636',
  'lei': None},
 'israel_discount_bank': {'permid': None,
  'isin': 'IL0006912120',
  'viafid': '125764680',
  'lei': None},
 'mizrahi_tefahot_bank': {'permid': None,
  'isin': None,
  'viafid': '222814807',
  'lei': None},
 'first_international_bank_of_israel': {'permid': None,
  'isin': None,
  'viafid': '124869969',
  'lei': None},
 'mauritius_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': '139419049',
  'lei': None},
 'cibanco': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'fidelity_bank_plc_': {'permid': None,
  'isin': None,
  'viafid': '142299121',
  'lei': None},
 'ecobank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'us_exim': {'permid': None, 'isin': None, 'viafid': '130175936', 'lei': None},
 'suntrust_bank': {'permid': None,
  'isin': 'US89832Q1094',
  'viafid': '138439186',
  'lei': 'JJKC32MCHWDI71265Z06'},
 'banco_mercantil_del_norte': {'permid': None,
  'isin': 'MXP370711014',
  'viafid': '160381157',
  'lei': None},
 'banco_votorantim': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'uk_export_finance': {'permid': None,
  'isin': None,
  'viafid': '310519906',
  'lei': None},
 'svenska_handelsbanken': {'permid': None,
  'isin': 'SE0000193120',
  'viafid': '125498310',
  'lei': None},
 'nykredit': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bankinter': {'permid': None,
  'isin': 'ES0113679I37',
  'viafid': '306351741',
  'lei': None},
 'e_sun_commercial_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': '549300AMYZRPPY6D9P76'},
 'efic': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'eksport_kredit_fonden': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'export_credit_norway': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'instituto_de_credito_oficial': {'permid': None,
  'isin': None,
  'viafid': '169758605',
  'lei': None},
 'national_bank_of_abu_dhabi': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'uk_green_investment_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bancoestado': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_jiangsu': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'credicorp': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'swedish_export_credit_corporation_sek': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'greenline_community_ventures_llc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'partnership_capital_growth': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'aspiration_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'business_development_bank_of_canada': {'permid': None,
  'isin': None,
  'viafid': '141840324',
  'lei': None},
 'envest_microfinance': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'globalance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'keene_advisors_inc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'lombard_odier': {'permid': None,
  'isin': None,
  'viafid': '153016344',
  'lei': None},
 'maanch': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'microvest_capital_management_llc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'assiniboine_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'vaya_finserv_private_limited': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'assimoco_spa': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'ara_consultants_limited': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'we_family_offices_llc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_muamalat_malaysia': {'permid': None,
  'isin': None,
  'viafid': '261506882',
  'lei': None},
 'bank_of_palestine_palestine': {'permid': None,
  'isin': None,
  'viafid': '123495085',
  'lei': None},
 'brac_bank_bangladesh': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'centerinvest_bank_russia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'amalgamated_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'tomorrow_gmbh': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'banco_ademi_dominican_republic': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_de_antigua_guatemala': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'nationwide': {'permid': None,
  'isin': None,
  'viafid': '156863205',
  'lei': None},
 'banco_codesarrollo_ecuador': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bancoestado_microempresas': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bankvic': {'permid': None, 'isin': None, 'viafid': '308253681', 'lei': None},
 'beneficial_state_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'big_path_capital': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'brattleboro_savings__loan': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'charity_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'circle_alliance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'city_first_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'clearwater_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'coast_capital_savings': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'credit_cooperatif': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'cultura_bank': {'permid': None,
  'isin': None,
  'viafid': '9697149296178980670008',
  'lei': None},
 'duca_financial_services_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'caisse_depargne_normandie': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'habito': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'la_nef': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'lead_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'libro_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'mascoma_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'national_cooperative_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'omista_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'shine': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'southern_bancorp_inc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'spring_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'sunrise_banks': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'teachers_mutual_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'triodos_netherlands': {'permid': None,
  'isin': None,
  'viafid': '156175718',
  'lei': '724500PMK2A2M1SQQ228'},
 'umweltbank': {'permid': None,
  'isin': 'DE0005570808',
  'viafid': None,
  'lei': None},
 'bank_australia': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'awa_alliance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banque_raiffeisen_region_geneve_rhone': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bdcu_alliance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'beyond_bank_australia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'obank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'piscataqua_savings_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'raiffeisen_servizi_assicurativi_srl': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'cooperative_bank_of_karditsa': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'folke_sparekassen': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'freie_gemeinschaftsbank_genossenschaft': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'magnet_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'merkur_resource_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_mundo_mujer_colombia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_popular_honduras': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banco_solidario_ecuador': {'permid': None,
  'isin': None,
  'viafid': '150653876',
  'lei': None},
 'bancompartir_colombia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bancosol_bolivia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banfondesa_dominican_republic': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'caja_arequipa_peru': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'card_bank_inc_philippines': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'centenary_bank_uganda': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'cooperativa_abaco_peru': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'daiichi_kangyo_credit_cooperative_japan': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'decorah_bank_and_trust_co': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'ecology_building_society_united_kingdom': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'esaf_small_finance_bank_india': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'grooming_microfinance_bank_nigeria_1': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'kindred_credit_union_canada': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'lapo_microfinance_bank_nigeria': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'megabank_ukraine_1': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'muktinath_bikas_bank_ltd_nepal': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'nmb_bank_limited_nepal': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'north_east_small_finance_bank_india': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'opportunity_bank_serbia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'opportunity_savings_and_loans_ghana_1': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sac_apoyo_integral_sa_el_salvador': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'the_first_microfinance_bank_afghanistan_afghanistan': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'the_first_microfinance_bank_tajikistan_tajikistan': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'vancity_canada': {'permid': None,
  'isin': None,
  'viafid': '141841747',
  'lei': None},
 'verity_cu_usa': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'vision_banco_paraguay': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'vsecu_vermont_state_employees_credit_union_usa': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'xacbank_mongolia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'federal_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'pnb': {'permid': None, 'isin': None, 'viafid': '133754357', 'lei': None},
 'sbi': {'permid': None,
  'isin': 'US8565522039',
  'viafid': '138999607',
  'lei': None},
 'yes_bank': {'permid': None,
  'isin': 'INE528G01019',
  'viafid': '150452003',
  'lei': None},
 'small_and_medium_enterprise_development_bank_of_thailand': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'government_housing_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'government_savings_bank': {'permid': None,
  'isin': None,
  'viafid': '145758956',
  'lei': None},
 'tisco_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'kiatnakin_phatra_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_of_ayudhya': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'kasikornbank': {'permid': None,
  'isin': 'TH0016010009',
  'viafid': None,
  'lei': None},
 'siam_commercial_bank': {'permid': None,
  'isin': 'TH0015010R16',
  'viafid': '141972924',
  'lei': None},
 'bank_of_agriculture_and_agricultural_cooperatives': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'krungthai_bank': {'permid': None,
  'isin': 'TH0150010Z03',
  'viafid': '266683910',
  'lei': None},
 'tmb_bank_tmb': {'permid': None,
  'isin': 'TH0068010014',
  'viafid': '173151050123233411888',
  'lei': None},
 'stadtsparkasse_dusseldorf': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'hypovereinsbank': {'permid': None,
  'isin': None,
  'viafid': '138873639',
  'lei': '2ZCNRR8UK83OBTEK2170'},
 'dkb': {'permid': None,
  'isin': None,
  'viafid': '152245891',
  'lei': '529900K16YGKC8BES892'},
 'deutsche_apothekerund_arztebank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sparkasse_koinbonn': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'paxbank': {'permid': None,
  'isin': None,
  'viafid': '146099460',
  'lei': '529900SCADYND9KVP627'},
 'kdbank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'ethik_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'permata_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_bjb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'mandiri_bank_mandiri': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bni': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bca': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_bri': {'permid': None,
  'isin': 'ID1000118201',
  'viafid': '156682623',
  'lei': None},
 'van_lanschot': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'argenta': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'vdk_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'safra': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bv': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'federal_savings_bank_caixa': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'handelsbanken': {'permid': None,
  'isin': 'SE0000193120',
  'viafid': '125498310',
  'lei': None},
 'sparebank_1_smn': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sparebank_1_nordnorge': {'permid': None,
  'isin': 'NO0006000801',
  'viafid': '231157245',
  'lei': None},
 'klp': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'sandnes_sparebank': {'permid': None,
  'isin': 'NO0006001007',
  'viafid': '4336148997642759870000',
  'lei': None},
 'sparebanken_vest': {'permid': None,
  'isin': 'NO0006000900',
  'viafid': '5611149068583665730001',
  'lei': None},
 'sparebank_1_ostlandet': {'permid': None,
  'isin': None,
  'viafid': '4492151247947744270002',
  'lei': None},
 'storebrand': {'permid': None,
  'isin': 'NO0003053605',
  'viafid': '1033149296225580670004',
  'lei': None},
 'japan_post_bank': {'permid': None,
  'isin': 'JP3946750001',
  'viafid': '255249668',
  'lei': '5493006JVO6N2HC2XZ76'},
 'resona': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'mizuho_bank': {'permid': None,
  'isin': None,
  'viafid': '260907608',
  'lei': 'RB0PEZSDGCO3JS6CEU02'},
 'bunq': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'lansforsakringars': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'skandia': {'permid': None, 'isin': None, 'viafid': '153060699', 'lei': None},
 'handesbanken': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'swedenbank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'jak_medlemsbank': {'permid': None,
  'isin': None,
  'viafid': '191551454',
  'lei': None},
 'abbey_national_santander': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'alliance__leicester_santander': {'permid': None,
  'isin': None,
  'viafid': '144500708',
  'lei': None},
 'carter_allen_santander': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'clydesdale_bank_virgin_money': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'coutts_rbs': {'permid': None,
  'isin': None,
  'viafid': '144687131',
  'lei': None},
 'cumberland_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'first_direct_hsbc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'first_national_santander': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'hbos__bank_of_scotland_lloyds': {'permid': None,
  'isin': None,
  'viafid': '143331899',
  'lei': None},
 'halifax_lloyds': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'intelligent_finance_lloyds_banking': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'john_lewis_partnership_card_hsbc': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'ms_bank_hsbc': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'metro_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'monzo': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'rbs': {'permid': '8589934212',
  'isin': 'GB00B7T77214',
  'viafid': '129626522',
  'lei': None},
 'revolut': {'permid': None,
  'isin': None,
  'viafid': '5021153532469248820005',
  'lei': None},
 'starling_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'tsb_banco_sabadell': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'ulster_bank_rbs': {'permid': None,
  'isin': None,
  'viafid': '127140899',
  'lei': None},
 'virgin_money': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'yorkshire_bank_virgin_money': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_of_melbourne': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'banksa': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bankwest': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'rams': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'st_george': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'ubank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'amp': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_queensland': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 '86_400': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'adelaide_bank': {'permid': None,
  'isin': None,
  'viafid': '150609068',
  'lei': None},
 'australian_military_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'australian_mutual_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'australian_unity_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'auswide_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_us_formerly_be': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bcu': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_first': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_heritage_isle': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bankstown_city_unity_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bendigo_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bnk_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'border_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'broken_hill_community_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'cairns_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'capricornian': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'central_murray_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'central_west_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'coastline_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'country_first_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'credit_union_sa': {'permid': None,
  'isin': None,
  'viafid': '308254065',
  'lei': None},
 'cua_credit_union_australia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'dalby_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'defence_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'delphi_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'dnister_ukrainian_credit_cooperative': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'endeavour_mutual_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'family_first_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'fire_brigades_employees_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'firefighters_credit_cooperative': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'firefighters_mutual_bank_formerly_fire_board_nsw_employees_credit_union__fire_brigades_employees_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'fire_service_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'first_choice_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'first_option_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'gc_mutual_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'gateway_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'geelong_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'goldfields_money': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'goulburn_murray_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'greater_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'gympie_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'health_professionals_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'heritage_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'horizon_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'hume_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'hunter_united': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'illawarra_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'imb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'judo_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'laboratories_credit_union_lcu': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'lll_lutheran_laypeoples_league_of_australia': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'lysaght_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'macarthur_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'macquarie_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'maleny_credit_union_mcu': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'me_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'move_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'mystate_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'newcastle_permanent': {'permid': None,
  'isin': None,
  'viafid': '149436455',
  'lei': None},
 'northern_inland_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'nova_alliance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'orange_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'pn_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'peoples_choice_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'pepper_money': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'police_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'police_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'pulse_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'qudos_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'qbank_formerly_queensland_police_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'queensland_country_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'racq_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'regional_australia_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'reliance_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'rural_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'service_one_alliance_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'south_west_slopes_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'southern_cross_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'south_west_credit': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'summerland_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sydney_mutual_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'the_mutual_bank_maitland_mutual': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'traditional_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'mylife_myfinance': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'transport_mutual_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'tyro': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'unibank_formerly_unicredit': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'unity_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'up_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'volt_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'warwick_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'waw_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'woolworths_employees_credit_union': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'unicredit_italy': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'sperekleees': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'piraeus': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'permanent_tsb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'otp_bank': {'permid': None,
  'isin': 'HU0000061726',
  'viafid': '148440435',
  'lei': None},
 'oikos': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'novo_banco': {'permid': None,
  'isin': None,
  'viafid': '43147121678726390421',
  'lei': None},
 'national_bank_of_greece': {'permid': '4295870369',
  'isin': 'GRS003003019',
  'viafid': None,
  'lei': None},
 'millennium_bcp': {'permid': None,
  'isin': 'PTBCP0AM0007',
  'viafid': '156497455',
  'lei': None},
 'ica_banken': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'helios': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'fortuna_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'flowe': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'fiare_banca_etica': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'fana_sparebank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'eurobank': {'permid': None,
  'isin': 'GRS323003012',
  'viafid': '157496525',
  'lei': None},
 'cib': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'banque_internationale_à_luxembourg': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'bank_of_ireland': {'permid': None,
  'isin': 'IE00BD1RP616',
  'viafid': '144252945',
  'lei': None},
 'bank_cler': {'permid': None,
  'isin': 'CH0018116472',
  'viafid': '126448447',
  'lei': None},
 'bank_austria': {'permid': None,
  'isin': 'AT0000995006',
  'viafid': '138850047',
  'lei': None},
 'st_george_bank': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'bank_of_scotland': {'permid': None,
  'isin': None,
  'viafid': '154128259',
  'lei': None},
 'john_lewis_finance': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'megabank_ukrania_1': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'triodos_belgium': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'triodos_germany': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'triodos_spain': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'triodos_united_kingdom': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'triodos_france': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'kiwibank': {'permid': None,
  'isin': None,
  'viafid': '129359625',
  'lei': None},
 'tsb': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'cooperative_nz': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'n26': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'allied_irish_bank': {'permid': None,
  'isin': None,
  'viafid': None,
  'lei': None},
 'alterna': {'permid': None, 'isin': None, 'viafid': None, 'lei': None},
 'meridian': {'permid': None, 'isin': None, 'viafid': None, 'lei': None}}

# make this a defaultdict
id_map = defaultdict(lambda: {'permid': None, 'isin': None, 'viafid': None, 'lei': None}, id_map)
