# these are the known aliases of banks.
# this mapping is not used for banktrack banks, but is used for other data sources.
# when banks are added to the dataset, their name is checked here.
# If their name is found in a key, they are assigned the tag (value).
# This is used to combine banks when they are identical, but with slightly different
# names in different data sources.
name_tag_map = {
 'Banco Itaú Unibanco': 'itau_unibanco',
 'KBC Bank': 'kbc',
 'The Co-operative Bank': 'the_co_operative_bank',
 'PNC Financial Services': 'pnc',
 'United Overseas Bank': 'uob',
 'Truist Financial': 'suntrust_bank',
 'Crédit Agricole Italia': 'credit_agricole_italia',
 'FriulAdria': 'credit_agricole_italia',
 'Carispezia': 'credit_agricole_italia',
 'Kantor Bank BNI Solok': 'kantor_bank_bni_solok',
 'Bank BNI Bandar Buat': 'kantor_bank_bni_solok',
 'Kantor Bank BNI Muaro Sijunjung': 'kantor_bank_bni_solok',
 'Kantor Bank BNI By Pass Padang': 'kantor_bank_bni_solok',
 'Sun Bank': 'bancosol_bolivia',
 'Meridian Credit Union': 'meridian',
 'Bank Filasṭīn': 'bank_of_palestine_palestine',
 'BNP Paribas': 'bnp_paribas',
 'BNP PARIBAS': 'bnp_paribas',
 'ABN AMRO': 'abn_amro',
 'ANZ': 'anz',
 'Banco Bradesco': 'banco_bradesco',
 'Banco do Brasil': 'banco_do_brasil',
 'Itaú-Unibanco': 'itau_unibanco',
 'Banco Santander': 'santander',
 'Bank Mandiri': 'bank_mandiri',
 'Bank of America': 'bank_of_america',
 'Bank of China': 'bank_of_china',
 'Barclays': 'barclays',
 'Mitsubishi UFJ Financial Group (MUFG)': 'bank_of_tokyo_mitsubishi_ufj',
 'MUFG': 'bank_of_tokyo_mitsubishi_ufj',
 'Citi': 'citi',
 'Credit Suisse': 'credit_suisse',
 'Deutsche Bank': 'deutsche_bank',
 'Goldman Sachs': 'goldman_sachs',
 'HSBC': 'hsbc',
 'JPMorgan Chase': 'jpmorgan_chase',
 'Société Générale': 'societe_generale',
 'Belfius': 'belfius',
 'ING': 'ing',
 'Intesa Sanpaolo': 'intesa_sanpaolo',
 'Fubon Financial Holding': 'fubon_financial_holdings',
 'Mizuho Financial Group': 'mizuho',
 'Westpac': 'westpac',
 'UBS': 'ubs',
 'Standard Chartered': 'standard_chartered',
 'KBC': 'kbc',
 'BBVA': 'bbva',
 'Morgan Stanley': 'morgan_stanley',
 'Nedbank': 'nedbank',
 'Rabobank': 'rabobank',
 'Royal Bank of Canada (RBC)': 'rbc',
 'NatWest Group': 'natwest',
 'Scotiabank': 'scotiabank',
 'China Construction Bank': 'china_construction_bank',
 'ICBC': 'industrial_commercial_bank_of_china',
 'Industrial and Commercial Bank of China (ICBC)': 'industrial_commercial_bank_of_china',
 'State Bank of India': 'state_bank_of_india',
 'Standard Bank': 'standard_bank',
 'Crédit Agricole': 'credit_agricole',
 'UniCredit': 'unicredit',
 'UniBank': 'unicredit',
 'Banco Galicia': 'banco_galicia',
 'Bank of Montreal (BMO)': 'bmo_financial_group',
 'Bank of Montreal': 'bmo_financial_group',
 'Banca Etica': 'banca_etica',
 'Alternative Bank Schweiz': 'alternative_bank_schweiz',
 'ASN Bank': 'asn_bank',
 'De Volksbank': 'de_volksbank',
 'GLS Bank': 'gls_bank',
 'Macquarie': 'macquarie_group',
 'OP Financial Group': 'op_financial_group',
 'BTG Pactual': 'btg_pactual',
 'The co-operative bank': 'the_co_operative_bank',
 'RSF Social Finance': 'rsf_social_finance',
 'Caixa Econômica Federal': 'caixa_economica_federal',
 'CaixaBank': 'CaixaBank',
 'Banco Popular Español': 'banco_popular_espanol',
 'Banco Espirito Santo': 'banco_espirito_santo',
 'Desjardins Group': 'caisse_de_economie_solidaire_desjardins',
 'Ekobanken': 'ekobanken',
 'China Development Bank': 'china_development_bank',
 'First Commercial Bank': 'first_commercial_bank',
 'Attijariwafa Bank': 'attijariwafa_bank',
 'Commercial International Bank (CIB)': 'commercial_international_bank_cib',
 'National Bank of Egypt': 'national_bank_of_egypt',
 'Jyske Bank': 'jyske_bank',
 'Sydbank': 'sydbank',
 'SpareBank 1 SR-Bank': 'sparebank_1_srbank',
 'Banque Populaire': 'banque_populaire',
 'Export-Import Bank of China': 'china_exim_bank',
 'China Everbright Bank': 'china_everbright_bank',
 'Canadian Imperial Bank of Commerce (CIBC)': 'cibc',
 'Manulife': 'manulife',
 'Nordea': 'nordea',
 'Zurich Kantonalbank': 'zurich_kantonalbank',
 'Toronto-Dominion Bank (TD Bank)': 'td_bank_financial_group',
 'TD': 'td_bank_financial_group',
 'Danske Bank': 'danske_bank',
 'Erste Group Bank': 'erste_group',
 'Wells Fargo': 'wells_fargo',
 'Commonwealth Bank': 'commonwealth_bank',
 'NAB': 'national_australia_bank_group',
 'National Australia Bank (NAB)': 'national_australia_bank_group',
 'National Australia Bank': 'national_australia_bank_group',
 'DekaBank': 'dekabank',
 'Natixis': 'natixis',
 'Commerzbank': 'commerzbank',
 'Industrial Bank': 'industrial_bank',
 'Bangkok Bank': 'bangkok_bank',
 'Kasikorn Bank': 'kasikorn_bank',
 'Absa Group': 'absa_bank_limited',
 'Access Bank': 'access_bank',
 'Arab African International Bank': 'arab_african_international_bank',
 'Banco de la República Oriental del Uruguay': 'banco_de_la_republica_oriental_del_uruguay',
 'India Exim Bank': 'export_import_bank_of_india',
 'Bancolombia': 'bancolombia_s_a_',
 'Bank Muscat': 'bank_muscat',
 'Itaú Corpbanca': 'corpbanca',
 'DNB': 'dnb',
 'Export Development Canada': 'export_development_canada',
 'FirstRand': 'firstrand_group_ltd',
 'FMO': 'fmo',
 'KfW IPEX-Bank': 'kfw_ipex_bank',
 'Lloyds Banking Group': 'lloyds_banking_group_plc',
 'Skandinaviska Enskilda Banken (SEB)': 'seb',
 'Garanti BBVA': 'garantibank',
 'Akbank': 'akbank',
 'BMCE Bank of Africa': 'bmce_bank',
 'Agricultural Bank of China': 'agricultural_bank_of_china',
 'PNC': 'pnc',
 'CIFI': 'cifi',
 'Shinhan Financial Group': 'shinhan_financial_group',
 'Shinhan': 'shinhan_financial_group',
 'Yuanta Commercial Bank': 'yuanta_commercial_bank',
 'Shinsei Bank': 'shinsei_bank',
 'Mianyang City Commercial Bank': 'mianyang_city_commercial_bank',
 'CTBC Bank': 'ctbc_bank',
 'Chongqing Rural Commercial Bank': 'chongqing_rural_commercial_bank',
 'Bank SinoPac': 'bank_sinopac',
 'Bank of Huzhou': 'bank_of_huzhou',
 'NIBC': 'nibc',
 'Ahli United Bank': 'ahli_united_bank',
 'Vnesheconombank': 'vnesheconombank',
 'Sberbank': 'sberbank',
 'Bank of Communications': 'bank_of_communications',
 'Hua Xia Bank': 'hua_xia_bank',
 'China Merchants Bank': 'china_merchants_bank',
 'Shanghai Pudong Development Bank': 'shanghai_pudong_development_bank',
 'China Minsheng Bank': 'china_minsheng_bank',
 'CITIC Bank International': 'citic_bank_international',
 'Axis Bank': 'axis_bank',
 'Industrial Development Bank of India (IDBI)': 'industrial_development_bank_of_india',
 'Alfa Bank': 'alfa_bank',
 'HDFC Bank': 'hdfc_bank',
 'ICICI Bank': 'icici_bank',
 'China CITIC Bank': 'china_citic_bank',
 'Ping An Bank': 'ping_an_bank',
 'Ping An': 'ping_an_bank',
 'Bank of Beijing': 'bank_of_beijing',
 'Bank of Ningbo': 'bank_of_ningbo',
 'Bank of Nanjing': 'bank_of_nanjing',
 'VTB': 'vtb_bank',
 'Maybank': 'maybank',
 'Banque Misr': 'banque_misr',
 'CIMB': 'cimb',
 'DBS': 'dbs',
 'OCBC Bank': 'ocbc',
 'United Overseas Bank (UOB)': 'uob',
 'Bank Rakyat Indonesia (BRI)': 'bank_rakyat_indonesia',
 'IDFC': 'idfc',
 'Otkritie Bank': 'otkritie_bank',
 'Banco de Crédito del Perú (BCP)': 'banco_de_credito_del_peru_bcp_',
 'DZ Bank': 'dz_bank',
 'Korea Development Bank (KDB)': 'korea_development_bank_kdc',
 'Norinchukin Bank': 'the_norinchukin_bank',
 'BNY Mellon': 'bny_mellon',
 'U.S. Bancorp': 'us_bancorp',
 'Suncorp': 'suncorp',
 'Suncorp Bank': 'suncorp',
 'La Banque Postale': 'la_banque_postale',
 'Allianz': 'allianz',
 'BayernLB': 'bayernlb',
 'Helaba': 'helaba',
 'HSH Nordbank': 'hsh_nordbank',
 'LBBW': 'lbbw',
 'Zenith Bank': 'zenith_bank',
 'NORD/LB': 'norddeutsche_landesbank_nordlb_',
 'Mediobanca': 'mediobanca',
 'Raiffeisen Bank International': 'raiffeisen_zentralbank',
 'Swedbank': 'swedbank',
 'Bank of India': 'bank_of_india',
 'Power Finance Corporation (PFC)': 'power_finance_corporation',
 'Life Insurance Corporation of India': 'life_insurance_corporation_of_india',
 'PKO Bank Polski': 'pko_bank_polski',
 'Bank Gospodarstwa Krajowego (BGK)': 'bank_gospodarstwa_krajowego',
 'Getin Noble Bank': 'getin_noble_bank',
 'Bank Millennium': 'bank_millennium',
 'Bank Central Asia': 'bank_central_asia',
 'Bank Danamon': 'bank_danamon',
 'Bank Gospodarki Żywnościowej': 'bank_gospodarki_ywno_ciowej',
 'Crédit Mutuel': 'credit_mutuel',
 'BNDES': 'bndes',
 'Bankia': 'bankia',
 'Norges Bank': 'norges_bank',
 'KfW': 'kfw',
 'BPCE': 'bpce_group',
 'BPCE/Natixis': 'bpce_group',
 'Wing Lung Bank': 'wing_lung_bank',
 'Cathay United Bank': 'cathay_united_bank',
 'Banco Sabadell': 'banco_sabadell',
 'Bank Hapoalim': 'bank_hapoalim',
 'Finnfund': 'finnfund',
 'Bank Leumi': 'bank_leumi',
 'Israel Discount Bank': 'israel_discount_bank',
 'Mizrahi Tefahot Bank': 'mizrahi_tefahot_bank',
 'First International Bank of Israel (FIBI)': 'first_international_bank_of_israel',
 'Mauritius Commercial Bank': 'mauritius_commercial_bank',
 'CIBanco': 'cibanco',
 'Fidelity Bank': 'fidelity_bank_plc_',
 'Ecobank': 'ecobank',
 'Export-Import Bank of the United States (EXIM)': 'us_exim',
 'Truist Bank': 'suntrust_bank',
 'Truist': 'suntrust_bank',
 'Banco Mercantil del Norte (Banorte)': 'banco_mercantil_del_norte',
 'Banco Votorantim': 'banco_votorantim',
 'UK Export Finance': 'uk_export_finance',
 'Svenska Handelsbanken': 'svenska_handelsbanken',
 'Nykredit Bank': 'nykredit',
 'Bankinter': 'bankinter',
 'E.SUN Commercial Bank': 'e_sun_commercial_bank',
 'Export Finance Australia': 'efic',
 'Denmarks Export Credit Agency': 'eksport_kredit_fonden',
 'Export Credit Norway': 'export_credit_norway',
 'Instituto de Crédito Oficial (ICO)': 'instituto_de_credito_oficial',
 'First Abu Dhabi Bank (FAB)': 'national_bank_of_abu_dhabi',
 'Green Investment Group': 'uk_green_investment_bank',
 'Banco del Estado de Chile': 'bancoestado',
 'Bank of Jiangsu': 'bank_of_jiangsu',
 'Credicorp': 'credicorp',
 'Swedish Export Credit Corporation (SEK)': 'swedish_export_credit_corporation_sek',
 'SMBC Group': 'smbc_group',
 'U.S. Bank': 'us_bancorp',
 'Postal Savings Bank of China': 'postal_savings_bank_of_china',
 'Greenline Community Ventures LLC': 'greenline_community_ventures_llc',
 'Partnership Capital Growth': 'partnership_capital_growth',
 'Aspiration Bank': 'aspiration_bank',
 'Business Development Bank of Canada': 'business_development_bank_of_canada',
 'Envest Microfinance': 'envest_microfinance',
 'Globalance Bank': 'globalance_bank',
 'Keene Advisors, Inc.': 'keene_advisors_inc',
 'Lombard Odier': 'lombard_odier',
 'Maanch': 'maanch',
 'MicroVest Capital Management, LLC': 'microvest_capital_management_llc',
 'Assiniboine Credit Union': 'assiniboine_credit_union',
 'Vaya Finserv Private Limited': 'vaya_finserv_private_limited',
 'Assimoco S.p.A.': 'assimoco_spa',
 'ARA Consultants Limited': 'ara_consultants_limited',
 'WE Family Offices LLC': 'we_family_offices_llc',
 'Bank Muamalat (Malaysia)': 'bank_muamalat_malaysia',
 'Bank of Palestine (Palestine)': 'bank_of_palestine_palestine',
 'BRAC Bank (Bangladesh)': 'brac_bank_bangladesh',
 'Center-Invest Bank (Russia)': 'centerinvest_bank_russia',
 'Amalgamated Bank': 'amalgamated_bank',
 'ASN': 'asn_bank',
 'Tomorrow GmbH': 'tomorrow_gmbh',
 'Banco Ademi (Dominican Republic)': 'banco_ademi_dominican_republic',
 'Banco de Antigua (Guatemala)  ': 'banco_de_antigua_guatemala',
 'Nationwide': 'nationwide',
 'Banco Codesarrollo (Ecuador)': 'banco_codesarrollo_ecuador',
 'BancoEstado Microempresas': 'bancoestado_microempresas',
 'BankVic': 'bankvic',
 'Beneficial State Bank': 'beneficial_state_bank',
 'Big Path Capital': 'big_path_capital',
 'Brattleboro Savings & Loan': 'brattleboro_savings__loan',
 'Charity Bank': 'charity_bank',
 'CIRCLE Alliance Bank': 'circle_alliance_bank',
 'City First Bank': 'city_first_bank',
 'Clearwater Credit Union ': 'clearwater_credit_union',
 'Coast Capital Savings': 'coast_capital_savings',
 'Co-op Bank': 'the_co_operative_bank',
 'Crédit Coopératif': 'credit_cooperatif',
 'Cultura Bank ': 'cultura_bank',
 'DUCA Financial Services Credit Union': 'duca_financial_services_credit_union',
 "caisse d'épargne Normandie": 'caisse_depargne_normandie',
 'GLS': 'gls_bank',
 'Habito': 'habito',
 'La Nef': 'la_nef',
 'Lead Bank ': 'lead_bank',
 'Libro Credit Union': 'libro_credit_union',
 'Mascoma Bank': 'mascoma_bank',
 'National Cooperative Bank ': 'national_cooperative_bank',
 'OMISTA Credit Union': 'omista_credit_union',
 'Shine': 'shine',
 'Southern Bancorp, Inc.': 'southern_bancorp_inc',
 'Spring Bank': 'spring_bank',
 'Sunrise Banks': 'sunrise_banks',
 'Teachers Mutual Bank': 'teachers_mutual_bank',
 'Umweltbank': 'umweltbank',
 'Bank Australia': 'bank_australia',
 'AWA Alliance Bank': 'awa_alliance_bank',
 'Banque Raiffeisen Région Genève Rhône': 'banque_raiffeisen_region_geneve_rhone',
 'BDCU Alliance Bank': 'bdcu_alliance_bank',
 'Beyond Bank Australia': 'beyond_bank_australia',
 'Beyond Bank': 'beyond_bank_australia',
 'O-Bank': 'obank',
 'Piscataqua Savings Bank': 'piscataqua_savings_bank',
 'Raiffeisen Servizi Assicurativi Srl': 'raiffeisen_servizi_assicurativi_srl',
 'Alternative Bank Switzerland': 'alternative_bank_schweiz',
 'Cooperative Bank of Karditsa': 'cooperative_bank_of_karditsa',
 'Folke Sparekassen': 'folke_sparekassen',
 'Freie Gemeinschaftsbank Genossenschaft': 'freie_gemeinschaftsbank_genossenschaft',
 'MagNet Bank': 'magnet_bank',
 'Merkur Resource Bank': 'merkur_resource_bank',
 'Banco Mundo Mujer (Colombia)': 'banco_mundo_mujer_colombia',
 'Banco Popular (Honduras)': 'banco_popular_honduras',
 'Banco Solidario (Ecuador) ': 'banco_solidario_ecuador',
 'Bancompartir (Colombia)': 'bancompartir_colombia',
 'BancoSol (Bolivia)': 'bancosol_bolivia',
 'BANFONDESA (Dominican Republic)': 'banfondesa_dominican_republic',
 "Caissed' economiesolidaire Desjardins (Canada)": 'caisse_de_economie_solidaire_desjardins',
 'Caja Arequipa (Peru)': 'caja_arequipa_peru',
 'CARD Bank, Inc. (Philippines)   ': 'card_bank_inc_philippines',
 'Centenary Bank (Uganda)': 'centenary_bank_uganda',
 'Cooperativa Abaco (Peru)': 'cooperativa_abaco_peru',
 'DAI-ICHI KANGYO Credit Cooperative (Japan)': 'daiichi_kangyo_credit_cooperative_japan',
 'Decorah Bank and Trust Co.': 'decorah_bank_and_trust_co',
 'Ecology Building Society (United Kingdom)': 'ecology_building_society_united_kingdom',
 'ESAF Small Finance Bank (India)': 'esaf_small_finance_bank_india',
 'Grooming Microfinance Bank (Nigeria) 1': 'grooming_microfinance_bank_nigeria_1',
 'Kindred Credit Union (Canada)': 'kindred_credit_union_canada',
 'LAPO Microfinance Bank (Nigeria)': 'lapo_microfinance_bank_nigeria',
 'MegaBank (Ukrania) 1': 'megabank_ukrania_1',
 'Muktinath Bikas Bank Ltd. (Nepal)': 'muktinath_bikas_bank_ltd_nepal',
 'NMB Bank Limited (Nepal)': 'nmb_bank_limited_nepal',
 'North East Small Finance Bank (India)': 'north_east_small_finance_bank_india',
 'Opportunity Bank (Serbia)': 'opportunity_bank_serbia',
 'Opportunity Savings and Loans (Ghana) 1': 'opportunity_savings_and_loans_ghana_1',
 'SAC Apoyo Integral, S.A. (El Salvador)': 'sac_apoyo_integral_sa_el_salvador',
 'The First Microfinance Bank Afghanistan (Afghanistan)': 'the_first_microfinance_bank_afghanistan_afghanistan',
 'The First Microfinance Bank Tajikistan (Tajikistan)': 'the_first_microfinance_bank_tajikistan_tajikistan',
 'Vancity (Canada)': 'vancity_canada',
 'Verity CU (USA)': 'verity_cu_usa',
 'Vision Banco (Paraguay)': 'vision_banco_paraguay',
 'VSECU (Vermont State Employees Credit Union) (USA) ': 'vsecu_vermont_state_employees_credit_union_usa',
 'XacBank (Mongolia)': 'xacbank_mongolia',
 'Triodos Bank N.V.': 'triodos_netherlands',
 'Triodos': 'triodos',
 'Triodos_Germany': 'triodos_germany',
 'Triodos_Spain': 'triodos_spain',
 'Triodos_United Kingdom': 'triodos_united_kingdom',
 'Triodos_France': 'triodos_france',
 'Triodos_Belgium': 'triodos_belgium',
 'Triodos_Netherlands': 'triodos_netherlands',
 'Federal Bank': 'federal_bank',
 'IOB': 'mediobanca',
 'PNB': 'pnb',
 'SBI': 'state_bank_of_india',
 'Yes Bank': 'yes_bank',
 'IDFC Bank': 'idfc',
 'Small and Medium Enterprise Development Bank of Thailand': 'small_and_medium_enterprise_development_bank_of_thailand',
 'Government Housing Bank': 'government_housing_bank',
 'Government Savings Bank': 'government_savings_bank',
 'TISCO Bank': 'tisco_bank',
 'Kiatnakin Phatra Bank': 'kiatnakin_phatra_bank',
 'Bank of Ayudhya': 'bank_of_ayudhya',
 'Kasikornbank': 'kasikorn_bank',
 'Siam Commercial Bank': 'siam_commercial_bank',
 'Bank of Agriculture and Agricultural Cooperatives': 'bank_of_agriculture_and_agricultural_cooperatives',
 'Krungthai Bank': 'krungthai_bank',
 'TMB Bank (TMB)': 'tmb_bank_tmb',
 'Stadtsparkasse Düsseldorf': 'stadtsparkasse_dusseldorf',
 'HypoVereinsbank': 'hypovereinsbank',
 'COMMERZBANK': 'commerzbank',
 'DKB': 'dkb',
 'Deutsche Apotheker-und Ärztebank': 'deutsche_apothekerund_arztebank',
 'Sparkasse KöInBonn': 'sparkasse_koinbonn',
 'Pax-Bank': 'paxbank',
 'KD-BANK': 'kdbank',
 'Ethik Bank': 'ethik_bank',
 'Permata Bank': 'permata_bank',
 'CIMB NIAGA': 'cimb',
 'bank bjb': 'bank_bjb',
 'Mandiri Bank (mandiri)': 'mandiri_bank_mandiri',
 'Danamon': 'bank_danamon',
 'BNI': 'bni',
 'BCA': 'bca',
 'BANK BRI': 'bank_rakyat_indonesia',
 'Van Lanschot': 'van_lanschot',
 'Argenta': 'argenta',
 'Vdk Bank': 'vdk_bank',
 'Safra': 'safra',
 'BV': 'bv',
 'BTG pactual': 'btg_pactual',
 'bradesco': 'banco_bradesco',
 'Federal Savings Bank (CAIXA)': 'federal_savings_bank_caixa',
 'Bank of Brazil (BANCO DO BRASIL)': 'banco_do_brasil',
 'Itaú': 'itau_unibanco',
 'Santander Brazil (Santander)': 'santander',
 'Sbanken-Handelsbanken': 'svenska_handelsbanken',
 'SpareBank 1 SMN': 'sparebank_1_smn',
 'SpareBank 1 Nord-Norge': 'sparebank_1_nordnorge',
 'KLP': 'klp',
 'Sandnes Sparebank': 'sandnes_sparebank',
 'Sparebanken Vest': 'sparebanken_vest',
 'SpareBank 1 Ostlandet': 'sparebank_1_ostlandet',
 'Storebrand': 'storebrand',
 'Japan Post Bank': 'japan_post_bank',
 'Resona': 'resona',
 'Mizuho Bank': 'mizuho',
 'Sumitomo Mitsui Trust Holdings': 'sumitomo_mitsui_trust_holdings',
 'Sumitomo Mitsui Trust': 'sumitomo_mitsui_trust_holdings',
 'SuMi TRUST': 'sumitomo_mitsui_trust_holdings',
 'SMBC Group': 'sumitomo_mitsui_banking_corporation',
 'Sumitomo Mitsui Banking Corporation (SMBC)': 'sumitomo_mitsui_banking_corporation',
 'Sumitomo Mitsui': 'sumitomo_mitsui_banking_corporation',

 'Mitsubishi UFJ': 'bank_of_tokyo_mitsubishi_ufj',
 'ABN Amro': 'abn_amro',
 'bunq': 'bunq',
 'seb': 'seb',
 'Länsförsäkringars': 'lansforsakringars',
 'Skandia': 'skandia',
 'Handesbanken': 'handesbanken',
 'Swedenbank': 'swedenbank',
 'JAK Medlemsbank': 'jak_medlemsbank',
 'Abbey National (Santander)': 'abbey_national_santander',
 'Alliance & Leicester (Santander)': 'alliance__leicester_santander',
 'Carter Allen (Santander)': 'carter_allen_santander',
 'Clydesdale Bank (Virgin Money)': 'clydesdale_bank_virgin_money',
 'Co-operative Bank': 'the_co_operative_bank',
 'Coutts (RBS)': 'coutts_rbs',
 'Coutts': 'coutts_rbs',
 'Cumberland Bank': 'cumberland_bank',
 'First Direct (HSBC)': 'first_direct_hsbc',
 'First National (Santander)': 'first_national_santander',
 'HBOS / Bank of Scotland (Lloyds)': 'hbos__bank_of_scotland_lloyds',
 'Halifax (Lloyds)': 'halifax_lloyds',
 'Intelligent Finance (Lloyds Banking)': 'intelligent_finance_lloyds_banking',
 'John Lewis Partnership Card (HSBC)': 'john_lewis_partnership_card_hsbc',
 'John Lewis Finance': 'john_lewis_finance',
 'Lloyds': 'lloyds_banking_group_plc',
 'M&S Bank (HSBC)': 'ms_bank_hsbc',
 'Metro Bank': 'metro_bank',
 'Monzo': 'monzo',
 'Natwest / RBS': 'natwest',
 'RBS / Natwest': 'rbs',
 'Revolut': 'revolut',
 'Santander': 'santander',
 'Starling Bank': 'starling_bank',
 'TSB (Banco Sabadell)': 'tsb_banco_sabadell',
 'Ulster Bank (RBS)': 'ulster_bank_rbs',
 'Virgin Money': 'virgin_money',
 'Yorkshire Bank (Virgin Money)': 'yorkshire_bank_virgin_money'}
